SECRET_KEY = '-$(n!fv=zb6+4(1-#xnl9#v^%x72s4g+%!p0nkpe@6a(bg92d3'

RECAPTCHA_PUBLIC_KEY = '6LdNWyQTAAAAADOF2SOV-EGyqXDpG6Jdldu8XWZB'
RECAPTCHA_PRIVATE_KEY = '6LdNWyQTAAAAAEuPGBbK4PxhdqKrx_s8l6eu5MTT'

SERVERBASE = ''
