"""
Django settings for cs project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.dirname(BASE_DIR))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #TODO check correct ALLOWED_HOSTS settings for transkribus.eu

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
     'formatters': {
        'request': {
            'format':'[%(asctime)s] - %(levelname)s - %(module)s : %(message)s' ,
	    'datefmt' : '%d/%b/%Y %H:%M:%S'

        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter' : 'request',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARN'),
        },
    },
}

ALLOWED_HOSTS = ['transkribus.eu']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
#Supporting apps
    'bootstrap3',
    'captcha',
#project app
    'cs',
#READ apps
#    'apps.utils',
#    'apps.library',
#    'apps.dashboard',
#    'apps.edit',
#    'apps.search',
#    'apps.navigation'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #Added for READ
    'django.middleware.locale.LocaleMiddleware',

]
#'django.contrib.auth.middleware.SessionAuthenticationMiddleware' ??

ROOT_URLCONF = 'cs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, '../templates'),  ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #Added for READ
                'apps.utils.contexts.appname',
                'apps.utils.contexts.urlname',
		'apps.utils.contexts.apphead',
		'apps.utils.contexts.nav_up',
            ],
            'libraries' : {
                'read_tags': 'apps.utils.templatetags',
            },
        },
    },
]



WSGI_APPLICATION = 'cs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '../tmp/db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

#Added for READ locale directory for translations
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

LANGUAGE_CODE = 'en'
#Added for READ lang set == official EU languages
from django.utils.translation import ugettext_lazy as _
LANGUAGES = [
        ('bg', _('Bulgarian')),
        ('hr', _('Croatian')),
        ('cs', _('Czech')),
        ('da', _('Danish')),
        ('nl', _('Dutch')),
        ('en', _('English')),
        ('et', _('Estonian')),
        ('fi', _('Finnish')),
        ('fr', _('French')),
        ('de', _('German')),
        ('el', _('Greek')),
        ('hu', _('Hungarian')),
        ('ga', _('Irish')),
        ('it', _('Italian')),
        ('lv', _('Latvian')),
        ('lt', _('Lithuanian')),
#       ('mt', _('Maltese')), NO MALTESE IN DJANGO!
        ('pl', _('Polish')),
        ('pt', _('Portuguese')),
        ('ro', _('Romanian')),
        ('sk', _('Slovak')),
        ('sl', _('Slovenian')),
        ('es', _('Spanish')),
        ('sv', _('Swedish')),
];

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#### NB this is the static files setting for the production apache server

#Step 1: we store static files in project_root/static
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)
#Step 2 we also store static files in static directories in the apps
# and these finders will find them for us
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
#Step 3 We run python manage.py collectstatic it will collect the static files from the locations defined above
# and store them in the location defined by STATIC_ROOT (cannot be the same as any of the STATFILES_DIRS)
STATIC_ROOT =  'collected_static'
MEDIA_ROOT = 'media' #not currently used
#Step 4 Finally we tell django how to serve the static files
STATIC_URL = '/readTest/static/'
MEDIA_URL = '/readTest/media/' #not currently used

##################### Added for READ ###################

## Auth backend that logs in to transkribus.eu and extends the django.contrib.auth.User
AUTHENTICATION_BACKENDS = [
    'apps.utils.backends.TranskribusBackend',
]

#Location of TRP server for transkribus REST services
TRP_URL = 'https://transkribus.eu/TrpServer/rest/'

NOCAPTCHA = True

LOGIN_URL = 'login'

#Where to on login if no next param available?
LOGIN_REDIRECT_URL = '/dashboard'

#Default for size of paged data
PAGE_SIZE_DEFAULT = 5

### Manage static resources ###

#Switch to use CDNs or local
USE_CDNS = True
# Static Resources (js css etc)
CDNS = {'bootstrap_css' : {'local': "/static/css/bootstrap.min.css", 'cdn' : "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" },
       'bootstrap_js' : {'local': "/static/js/bootstrap.min.js", 'cdn' : "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"},
       'datatables_css' : {'local': "/static/css/jquery.dataTables.min.css", 'cdn': "//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css"},
       'datatables_js' : {'local': "/static/js/jquery.dataTables.min.js", 'cdn': "//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"},
       'jquery' : {'local' : "/static/js/jquery.js", 'cdn': "//code.jquery.com/jquery-1.12.3.js" },
       'jquery_ui' : {'local' : "/static/js/jquery-ui.min.js", 'cdn': "//code.jquery.com/ui/1.12.1/jquery-ui.min.js" },
       'jquery_ui_css' : {'local' : "/static/css/jquery-ui.css", 'cdn' : "//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" },
       'chart_js' : {'local': "/static/js/Chart.bundle.min.js", 'cdn': "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.bundle.min.js"},

      }


PROFILE_LOG_BASE = '/tmp/'


